version: '3'
services:
  mysql-standalone:
    image: 'mysql:8.0'
    volumes:
      - db-data:/var/lib/mysql
      - ./aarria.sql:/docker-entrypoint-initdb.d/dump.sql

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=aarria
    ports:
      - 3307:3306
    networks:
      - backend
    expose:
      - '3306'

  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/aarria?useSSL=false&useJDBCComplaintTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:

